
package jee.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.2.2
 * Fri Mar 23 13:57:13 CET 2018
 * Generated source version: 3.2.2
 */

@XmlRootElement(name = "trouverVisite", namespace = "http://jee/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trouverVisite", namespace = "http://jee/")

public class TrouverVisite {

    @XmlElement(name = "arg0")
    private jee.Visite arg0;

    public jee.Visite getArg0() {
        return this.arg0;
    }

    public void setArg0(jee.Visite newArg0)  {
        this.arg0 = newArg0;
    }

}

